### ISSUE TITLE
Fix appearance for radios with big names

### ISSUE THREAD

**Issue by btd1337** [ranfdev/raddiu#18]
Normal Name:

![Captura de tela de 2019-06-22 17-33-00](https://user-images.githubusercontent.com/11943860/59968724-bd572400-9514-11e9-86dc-2b4c941bda22.png)

Big Name:

![Captura de tela de 2019-06-22 17-33-13](https://user-images.githubusercontent.com/11943860/59968729-c516c880-9514-11e9-84e9-a6f514743a2c.png)

See [word-wrap property](https://webdesignerwall.com/tutorials/word-wrap-force-text-to-wrap) maybe this will help you.

**Comment by ranfdev** [comment]
Thanks for the report, i will fix it

**Comment by ranfdev** [comment]
fixed in commit d3a0fc4
