### ISSUE TITLE
AppCenter installation failed: unmet dependency "mpv"

### ISSUE THREAD

**Issue by imasaru** [ranfdev/raddiu#22]
**This issue, similar to #3, concerns the dependency `mpv`, but addresses its interference with installation as a defined dependency.**

I attempted to install Raddiu from AppCenter and got (text in the middle):
![image](https://user-images.githubusercontent.com/10376491/67163815-fd9aa780-f338-11e9-98bd-89cc8a40b82a.png)
When I try to install dependency `mpv`, I find that a whole list of _its_ own dependencies is "uninstallable":

![image](https://user-images.githubusercontent.com/10376491/67164031-bcf05d80-f33b-11e9-84c4-f2f960916205.png)

I was able to solve this issue by adding Doug McMahon's [`mpv-tests` PPA](https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests) on Launchpad as listed on the [mpv.io website](https://mpv.io/installation/) for Linux packages, which, I assume, provided the "uninstallable packages." As cassidyjames said in #3:

>@cassidyjames [said](https://github.com/ranfdev/raddiu/issues/3):
>
> Throwing a dialog about unmet dependencies that aren't in the stock elementary OS install and directing users to the Terminal to install them is not a great user experience; instead, you should include any necessary dependencies in your Debian packaging to ensure they're automatically installed along with your app.

**Comment by imasaru** [comment]
Hmm, I attempted installing Raddiu on another Elementary system from AppCenter and it successfully installed. Could it be a repo issue with my Juno? Unless anyone else has this problem, I will close this issue.

**Comment by ranfdev** [comment]
This is not an issue related to raddiu. As you said, the problem was probably related to your repos.
Raddiu has an explicit dependency on mpv, so when you install the program, apt automatically installs mpv for you. I don't know what went wrong here.
